---
- name: Install the application
  hosts: all
  become: true
  vars:
    app_version: 1.0.0

  tasks:
  - name: Update packages
    apt:
      update_cache: true
    tags: [ 'never' ]

  - name: Create installation directory
    file:
      path: /var/rt
      state: directory

  - name: Copy the application package
    copy:
      src: "{{ item }}"
      dest: /var/rt
      mode: +x
    with_fileglob:
      - target/radome-tester-*.jar

  # Docs https://www.raspberrypi.org/documentation/linux/usage/systemd.md
  - name: Create the service template
    template:
      src: ansible_templates/rt.service.j2
      dest: /etc/systemd/system/rt.service

  - name: Start service
    service:
      name: rt
      state: restarted

  - name: Wait for api to come up
    uri:
      url: "http://localhost:8080/"
      status_code: 200
    register: result
    until: result.status == 200
    retries: 60
    delay: 1
